### ISSUE TITLE
Build errors because onSemanticsAction doesn't exist anymore

### ISSUE THREAD

**Issue by larsb24** [jpnurmi/mnemonic_label#2]
The Flutter Team has removed onSemanticsAction in favour of onSemanticsActionEvent.
This unfortunately breaks this package.
Ref: https://github.com/flutter/engine/pull/42579

**Comment by jpnurmi** [comment]
Oh, I didn't know someone was using this. :) I originally thought it would be an important feature on the desktop but stopped working on this after talking to some UX and accessibility experts at Canonical who didn't seem to think so. Mnemonics are getting less common in modern GNOME, and Apple deprecated them in macOS ten years ago...

**Comment by larsb24** [comment]
Alright, I guess we don't need it that much and it makes sense to follow the advice of UX experts.
